# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  WORKDIR: $PWD
  RCLONE_IGNORE: >
    --exclude ".direnv/**"
    --exclude ".nix-env/**"
    --exclude ".venv/**"

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}, {{.WORKDIR}}"
    # silent: true

  profile-build:
    cmds:
      - nix build .#devEnv --out-link .nix-env
    sources:
      - flake.nix
      - flake.lock
    generates:
      - .nix-env

  rclone:
    cmds:
      - rclone sync {{.WORKDIR}} cds:Documents/progs/control-pcgrl {{.RCLONE_IGNORE}}
  
  check:
    cmds:
      - rclone check {{.WORKDIR}} cds:Documents/progs/control-pcgrl {{.RCLONE_IGNORE}}

# --exclude ".git/**"
